name: UserRepositoryFor-AWSBedrock-CodeReview
run-name: ${{ github.actor }} is doing an AWS Bedrock Code Review
on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  UserRepositoryFor-AWSBedrock-CodeReview-Job:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout repository
         uses: actions/checkout@v2
       - name: Set up AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-west-2
       - name: Clone the repository 
         run: git clone https://github.com/7empestx/AWSBedrock-CodeReview.git
       - name: Run npm start
         working-directory: ./AWSBedrock-CodeReview
         run: | 
              npm install 
              npm run start
       - name: List files in the repository
         run: |
          ls ${{ github.workspace }}
       - run: echo "🍏 This job's status is ${{ job.status }}."
