name: UserRepositoryFor-AWSBedrock-CodeReview
run-name: ${{ github.actor }} is doing an AWS Bedrock Code Review
on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  UserRepositoryFor-AWSBedrock-CodeReview-Job:
    runs-on: ubuntu-latest
    steps:
       - name: Set up AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-west-2

       - name: Checkout user repo code
         uses: actions/checkout@v2

       - name: Clone the action code repository 
         run: git clone https://github.com/7empestx/AWSBedrock-CodeReview.git

       - name: Get diff
         run: |
           git fetch origin main
           echo "DIFF=$(git diff FETCH_HEAD)" >> $GITHUB_ENV

       - name: Run npm start on action code
         working-directory: ./AWSBedrock-CodeReview
         run: | 
              npm install 
              npm run start

       - name: List files in the workspace
         run: |
          ls ${{ github.workspace }}
       - run: echo "🍏 This job's status is ${{ job.status }}."
